version: "3.8"
name: react-tutorial
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - ./../src:/home/node